### ISSUE TITLE
Languege Undefined causes stylesheet to not apply

### ISSUE THREAD

**Issue by Blue-Pilkinton-Ching** [markedjs/marked-highlight#197]
Consider the code:

`  markedHighlight({
    langPrefix: 'hljs ',
    highlight(code, lang) {
      const language = hljs.getLanguage(lang) ? lang : 'plaintext'
      return hljs.highlight(code, { language }).value
    },
  })`
  
If hljs.getLanguage(lang) === undefined, then the langPrefix classes are not applied to the codeblock including 'hljs'. This means that the formatting for the code block breaks.

Below images, are examples of formatting working, broken, and what it should look like if hljs class was still aplied correctly.

![image](https://github.com/markedjs/marked-highlight/assets/49179161/a86e42fa-3563-45bd-b283-d2e8940a7bfc)
![image](https://github.com/markedjs/marked-highlight/assets/49179161/fd60e66a-70da-4f4e-b8c2-0497c63643f0)
![image](https://github.com/markedjs/marked-highlight/assets/49179161/ed9d6bd6-1830-4d3e-8e68-05d65cb3ab91)

In the middle image, you can see that the class "hljs" isn't applied to the code block. And so, it doesn't get the proper background color and padding that it should have as seen in the bottom image. (bottom image had the hljs class applied manually)

**Comment by UziTech** [comment]
Sounds like a problem for hljs. We don't supply any styles.

**Comment by Blue-Pilkinton-Ching** [comment]
> Sounds like a problem for hljs. We don't supply any styles.

Looks like it. Cheers!
