### ISSUE TITLE
deprecation warning when using this package.

### ISSUE THREAD

**Issue by RoenLie** [markedjs/marked-highlight#24]
_Edit as my initial assumption was slightly off_

After upgrading to marked v5, I started encountering deprecation warnings for how I was using code block highlighting.

After following the deprecation warning and updating this package. I was still encountering the same deprecation warning.

It appears that this package is setting langPrefix to "", which triggers the deprecation warning.

![image](https://github.com/markedjs/marked-highlight/assets/52429191/9f4f0789-8dca-45b9-9393-e70f489124d2)

![image](https://github.com/markedjs/marked-highlight/assets/52429191/d04f0030-debc-4a1d-8c22-bf17a87339a2)

**Comment by UziTech** [comment]
Thanks for reporting this! :100:

Initially marked v5 warn for deprecation if langPrefix was not falsey but that was fixed in v5.0.1 and I forgot to update this package.
