### ISSUE TITLE
Consider adding a note for `mangle` and `headerIds`

### ISSUE THREAD

**Issue by octref** [markedjs/marked-highlight#27]
Hi, when I'm using this plugin with marked, it shows this error:

```
marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
```

I can confirm this is fixed by setting these two options: https://github.com/markedjs/marked/releases/tag/v5.0.1

Adding a note in readme can be helpful!

**Comment by UziTech** [comment]
I think release notes is a better place for this. This won't be the case for much longer. We just wanted to let people know those options that are on by default are deprecated and will be removed in the future.

**Comment by octref** [comment]
Alright thanks!
