### ISSUE TITLE
Namespace has no exported member "MarkedExtension"

### ISSUE THREAD

**Issue by thooyork** [markedjs/marked-highlight#33]
I was using highlight in marked.parse like so:

`
marked.parse(input, {
         highlight: function (code, lang) {
         return highlightjs.highlightAuto(code).value;
        },
        async: true,
      }) `

And because of the deprecaion warning I changed it to this:

` marked.use(
      markedHighlight({
        highlight: function (code, lang) {
          return highlightjs.highlightAuto(code).value;
        },
      }),
    );`

However when building my application I get the following error:

../node_modules/marked-highlight/src/index.d.ts(68,82): error TS2694: Namespace '"/home/myApp/node_modules/@types/marked/index"' has no exported member 'MarkedExtension'.

I already updated the typedefinitions of marked to "@types/marked": "^5.0.0",
and I tried several settings in tsconfig, but nothing helped.

**Comment by thooyork** [comment]
This behaviour occurs in release 2.0.0 - After downgrading to 1.0.2 it worked. Hope that helps.

**Comment by UziTech** [comment]
@toastwaffle this seems to be an issue with the types that were added

**Comment by toastwaffle** [comment]
Hey @thooyork 

Could you do the following so I have a bit more information:

- Please confirm exactly which versions of `marked`, `marked-highlight`, and `@types/marked` you have installed.
- Please check the `/home/myApp/node_modules/@types/marked/index.d.ts` file, and see if contains `MarkedExtension` anywhere in it
- Please tell us how you are building your project

**Comment by toastwaffle** [comment]
Also, which version of typescript are you using?

**Comment by thooyork** [comment]
Ok, versions I am using are:

node: 18.16.0
npm: 9.5.1

marked: 5.0.2
marked-highlight: 2.0.0 was not working now downgraded to 1.0.2
@types/marked: 5.0.0
typescript: 5.0.4

index.d.ts file does contain an interface "MarkedExtension"

The project utilizes vue.js in Frontend and node.js in Backend build with lerna.

Hope that helps.

**Comment by floscher** [comment]
I prepared a branch https://github.com/fumiX/fuBlog/tree/marked-highlight-issue showing the issue.

The error message occurs at https://github.com/fumiX/fuBlog/actions/runs/5078822016/jobs/9123832108#step:6:17 when running `npm run build` on the project.

The version before https://github.com/fumiX/fuBlog/commit/c899b436c28c1277c2cfdf41eca9b5431d094a65 ran successfully with marked-highlight `1.0.2`.

**Comment by floscher** [comment]
@toastwaffle thank you for the fix! It now works indeed :tada:
