### ISSUE TITLE
markedHighlight bind to wrong place

### ISSUE THREAD

**Issue by storytellerF** [markedjs/marked-highlight#58]
When I use marked-highlight at pure javascript.
<img width="1501" alt="截屏2023-06-25 19 01 48" src="https://github.com/markedjs/marked-highlight/assets/34095089/25bf2480-720a-4513-afc5-8b13a5aafb2a">
<img width="344" alt="截屏2023-06-25 19 03 57" src="https://github.com/markedjs/marked-highlight/assets/34095089/5d45f6e1-ae59-41d3-9d8a-7a0042fdf374">

**Comment by UziTech** [comment]
Ya the umd script still requires restructuring like

```js
const {markedHighlight} = markedHighlight;
```

If you want to create a PR to add this to the docs, that would be great. 😁👍
